#!/bin/bash

export LD_LIBRARY_PATH=./share/gnu/lib:$LD_LIBRARY_PATH

APP=./bin/enum-debug
COEFFS="-coeffs 1,0"
DIVISORS="-divisors 11,11,11,11,11,11,11,11,11,1"
LOCKED="-locked 3"
DISC="-discriminant -285311670611"
TREE="-tree data/3511/tree_a1_0.txt"
INPUT="-input data/3511/p3e0mod3_a1_0.txt,data/3511/p5e0mod5_a1_0.txt,data/3511/p2e0mod4_a1_0.txt"
OUTPUT="-output output0011_test.txt"
PROGRESS="-progress prog.txt"

OMPI_OPTS="--mca btl ^usnic"
NP="-np 5"

mpirun $NP $OMPI_OPTS $APP $COEFFS $DIVISORS $DISC $INPUT $OUTPUT $TREE $LOCKED $PROGRESS
